[versions]
spigot-api = "1.14.4-R0.1-SNAPSHOT"
bstats = "3.0.0"
jetbrains-annotations = "23.0.0"

[libraries]
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
